export type FanArtItem = {
  src: string;
  author: string; // Xのユーザー名（フォルダ名）
};

// 自動生成: public/images/fan_arts 配下の画像を一覧化
export const fanArts: FanArtItem[] = [
  { src: "/images/fan_arts/nmkenji/maturi.png", author: "nmkenji" },
  { src: "/images/fan_arts/0235_jp/Generated_Image_August_30_2025_-_10_59AM.jpg", author: "0235_jp" },
  { src: "/images/fan_arts/mei_999_/Gemini_Generated_Image_oizcz0oizcz0oizc.png", author: "mei_999_" },
  { src: "/images/fan_arts/mei_999_/AJfQ9KRqy8zDrmQQDxQU0JnvYPBndicTiWWTTNjuDBHsT36iHNfFx2lCGuJgsO15NK2NsGFohoZRUkyYUvftPF8PPJfu_R1U7naD4co1vzpD3bU0hVsCNaaOEVZK9sCOmzIAVfl3LFMIwGJsr13vNKk6rGtrfhIQ4liCveFsHMeaKOKfOCNQeQs1024.png", author: "mei_999_" },
  { src: "/images/fan_arts/mei_999_/Generated_Image_August_31_2025_-_2_02PM.jpeg", author: "mei_999_" },
  { src: "/images/fan_arts/mei_999_/AJfQ9KT_b_8hXqf5XN__SaPVC7JqUuqiKVgw3unoexjCtlzHXfhqyXNui-fwE6dkxhpdr1QAQhibccSbSkix4zrQTy-cr7qrnIV5LcQfFpoaqmMxOh871J_j21TIwIuFLu4dSktzJ2a7i6SKvev7XjFOiXzUYLXMobYaZiJ8JBd3mQheu0mSegs1024.png", author: "mei_999_" },
  { src: "/images/fan_arts/mei_999_/3901309e-36f2-43a5-a947-575ac1418fd8.png", author: "mei_999_" },
  { src: "/images/fan_arts/mei_999_/Gemini_Generated_Image_3vctnp3vctnp3vct.png", author: "mei_999_" },
  { src: "/images/fan_arts/mei_999_/AJfQ9KRiCL_o1mSfd78iTKeeSbuQ1H7TmZfIciJe9aRRA0vu-CZFeh8BOAP9qXNdZfoQQiFI_y8v5F1dkWZpz6dWAXOeUbRo7nHqPVnvFX-MgpQ16mTsGVDVfYPnXYXn4fSqaxnFF5WtowzRrqs7duu6nTx3KX6Nb0YxV1CVYyc0A5NglwQas1024.png", author: "mei_999_" },
  { src: "/images/fan_arts/mei_999_/1756529447140.jpg", author: "mei_999_" },
  { src: "/images/fan_arts/mei_999_/1756748332873.jpg", author: "mei_999_" },
  { src: "/images/fan_arts/m_gen_chan/ComfyUI_up_x_01410_.png", author: "m_gen_chan" },
  { src: "/images/fan_arts/m_gen_chan/ComfyUI_up_x_00685_.png", author: "m_gen_chan" },
  { src: "/images/fan_arts/M1RA_A_Project/fdas.png", author: "M1RA_A_Project" },
  { src: "/images/fan_arts/M1RA_A_Project/Generated_Image_August_27_2025_-_7_01PM.png", author: "M1RA_A_Project" },
  { src: "/images/fan_arts/M1RA_A_Project/1.png", author: "M1RA_A_Project" },
  { src: "/images/fan_arts/KuboAvatar/Generated_Image_August_27_2025_-_12_42AM_1.jpeg", author: "KuboAvatar" },
  { src: "/images/fan_arts/KuboAvatar/Generated_Image_August_28_2025_-_12_31PM.jpeg", author: "KuboAvatar" },
  { src: "/images/fan_arts/KuboAvatar/1756633749-ry8PQm5CtjT4KH2IhfoALcdk.png", author: "KuboAvatar" },
  { src: "/images/fan_arts/KuboAvatar/Generated_Image_August_28_2025_-_5_18AM1.jpeg", author: "KuboAvatar" },
  { src: "/images/fan_arts/KuboAvatar/Generated_Image_August_28_2025_-_2_04AM.jpeg", author: "KuboAvatar" },
  { src: "/images/fan_arts/KuboAvatar/Generated_Image_August_28_2025_-_4_37AM.jpeg", author: "KuboAvatar" },
  { src: "/images/fan_arts/KuboAvatar/edited-adjusted-1756337912814.png", author: "KuboAvatar" },
  { src: "/images/fan_arts/KuboAvatar/Generated_Image_August_30_2025_-_12_50AM.jpeg", author: "KuboAvatar" },
  { src: "/images/fan_arts/KuboAvatar/1.png", author: "KuboAvatar" },
  { src: "/images/fan_arts/lab_tk2/file_00000000098c61f7ab6d6d06fe7fc28f.png", author: "lab_tk2" },
  { src: "/images/fan_arts/lab_tk2/Generated_Image_September_02_2025_-_11_29PM.jpg", author: "lab_tk2" },
  { src: "/images/fan_arts/lab_tk2/Generated_Image_August_30_2025_-_11_16PM.jpeg", author: "lab_tk2" },
  { src: "/images/fan_arts/lab_tk2/file_000000007b6061fa939cff09e1d34258.png", author: "lab_tk2" },
  { src: "/images/fan_arts/lab_tk2/file_00000000486461f7be0b1e05245c7b74.png", author: "lab_tk2" },
  { src: "/images/fan_arts/lab_tk2/Generated_Image_August_30_2025_-_8_53PM.jpeg", author: "lab_tk2" },
  { src: "/images/fan_arts/lab_tk2/4.jpg", author: "lab_tk2" },
  { src: "/images/fan_arts/lab_tk2/file_00000000c9b461fa8b2f1b8517958f88.png", author: "lab_tk2" },
  { src: "/images/fan_arts/lab_tk2/Generated_Image_August_31_2025_-_2_16AM.jpeg", author: "lab_tk2" },
  { src: "/images/fan_arts/xxx_めそ/Generated_Image_August_28_2025_-_8_05PM.jpeg", author: "xxx_めそ" },
  { src: "/images/fan_arts/xxx_めそ/Generated_Image_September_02_2025_-_10_11PM.jpeg", author: "xxx_めそ" },
  { src: "/images/fan_arts/xxx_めそ/Generated_Image_August_27_2025_-_7_58PM.jpeg", author: "xxx_めそ" },
  { src: "/images/fan_arts/xxx_めそ/2Q.png", author: "xxx_めそ" },
  { src: "/images/fan_arts/xxx_めそ/Generated_Image_August_31_2025_-_7_49PM.jpeg", author: "xxx_めそ" },
  { src: "/images/fan_arts/lilyAIstudy/Gy4O99ybIAAe0A1.jpeg", author: "lilyAIstudy" },
  { src: "/images/fan_arts/lilyAIstudy/GzMkqKFa8AAjy06.jpeg", author: "lilyAIstudy" },
  { src: "/images/fan_arts/lilyAIstudy/GzSL7dNaAAAxH16.jpeg", author: "lilyAIstudy" },
  { src: "/images/fan_arts/lilyAIstudy/Gyd_Jd8bwAAHTJV.jpeg", author: "lilyAIstudy" },
  { src: "/images/fan_arts/lilyAIstudy/GyT9VWSbsAA1oEz.jpeg", author: "lilyAIstudy" },
  { src: "/images/fan_arts/lilyAIstudy/GyOqI85aAAAUhXj.jpeg", author: "lilyAIstudy" },
  { src: "/images/fan_arts/lilyAIstudy/Gy2sO-4a0AERP_z.jpeg", author: "lilyAIstudy" },
  { src: "/images/fan_arts/lilyAIstudy/GzbQJgwXwAE4898.png", author: "lilyAIstudy" },
  { src: "/images/fan_arts/lilyAIstudy/Gzqga20bMAAZL8X.jpeg", author: "lilyAIstudy" },
  { src: "/images/fan_arts/lilyAIstudy/GyqVpgVacAILRVM.jpeg", author: "lilyAIstudy" },
  { src: "/images/fan_arts/lilyAIstudy/GzmUcRuboAAZMma.png", author: "lilyAIstudy" },
  { src: "/images/fan_arts/lilyAIstudy/Gx1WgDpasAAnCUn.jpeg", author: "lilyAIstudy" },
  { src: "/images/fan_arts/lilyAIstudy/GzgMDSHacAAMnEE.jpeg", author: "lilyAIstudy" },
  { src: "/images/fan_arts/lilyAIstudy/GyJqixMa8AArc9K.jpeg", author: "lilyAIstudy" },
  { src: "/images/fan_arts/lilyAIstudy/Gx6eAbfbYAAJMjk.jpeg", author: "lilyAIstudy" },
  { src: "/images/fan_arts/lilyAIstudy/GzCzZFzbcAErVXH.jpeg", author: "lilyAIstudy" },
  { src: "/images/fan_arts/lilyAIstudy/CleanShot 2025-09-03 at 13.00.30.png", author: "lilyAIstudy" },
  { src: "/images/fan_arts/lilyAIstudy/GylpBPEb0AA-pkr.jpeg", author: "lilyAIstudy" },
  { src: "/images/fan_arts/lilyAIstudy/Gz54nCubAAAYPKm.png", author: "lilyAIstudy" },
  { src: "/images/fan_arts/lilyAIstudy/Gy44IQKbMAAm-DB.jpeg", author: "lilyAIstudy" },
  { src: "/images/fan_arts/lilyAIstudy/GzvkJF-bgAIrJeV.png", author: "lilyAIstudy" },
  { src: "/images/fan_arts/lilyAIstudy/GzWeDzMa4AEQgVb.jpeg", author: "lilyAIstudy" },
  { src: "/images/fan_arts/lilyAIstudy/GzVLAgIa4AEeYjo.jpeg", author: "lilyAIstudy" },
  { src: "/images/fan_arts/lilyAIstudy/GyEWpNMa8AAJsSd.jpeg", author: "lilyAIstudy" },
]

